
sudo: required
dist: disty
language: node_js
node_js:
  - 'node'

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
- npm install

script: karma start karma.conf.js --single-run