
sudo: required
dist: disty
language: node_js
node_js:
  - 'node'

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
- npm install -g yarn --cache-min 999999999
- npm install -g angular-cli
- npm install -g karma
- npm install --no-optional

script: karma start karma.conf.js --single-run